config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :admins
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations" },
             path: "auth", path_names: { sign_in: 'login', sign_out: 'logout',
                                         password: 'secret', confirmation: 'verification',
                                         unlock: 'unblock', registration: 'register',
                                         sign_up: 'signup' }
  resources :users do
    resources :books do
      resources :chapters
    end
  end

  resources :books do
    resources :chapters
  end

  get 'home' => "catalog#index", as: :home
  get 'user/:user_id' => "users#show", as: :user_page
  get "user/:user_id/books/:book_id/add" => "books#add_chapter", as: :add_chapter
  get "user/:user_id/book/:book_id/chapter/:chapter_id/delete" => "books#delete_chapter", as: :delete_chapter

   root 'catalog#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  ratyrate_rateable "lol"
  validates :title, presence: true

  # validates :image_url, format: {
  #              with: %r{\.(gif|jpg|png)\Z}i,
  #              message: 'Only GIF/PNG/JPEG image formats are supported'
  #
  #          }



  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :positions, as: :positionable
  has_many :comments, as: :commentable
  has_many :tags
  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :add_chapter, :delete_chapter]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]

  def index
    @books = Book.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @book }
    end
  end

  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  def new
    @book =  Book.create(user_id: current_user.id, title: "No title")
  end

  def edit
  end

  def create
  @book = Book.update(book_params)
  @book.user_id = current_user.id
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_chapter
    @book.chapters.push Chapter.create(book_id: @book.id, title: "No title")
  end

  def delete_chapter
    @book.chapters.find(params[:chapter_id]).destroy
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(book_params)
        format.html { redirect_to @book, :notice => 'Book was successfully updated.' }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  def rate
    mark = params[:rate]
    if(rate > 0 && rate < 6)
      user = User.find_by_id(params[:user_id])
      book = Book.find_by_id(params[:book_id])
      rate = Rate.where(user_id: user.id, book_id: book.id).first
    end
  end




  def destroy
    @book.destroy
    @books = Book.all
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private

  def set_book
    @book = Book.find(params[:book_id] || params[:id])
  end

  def book_params
    params.require(:book).permit(
        :title, :user_id, :category,:tags,
        chapters_attributes: [:id, :text, :title, :done, :_destroy])
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def rating(book)
    book.rates.count > 0 ? book.rates.all.sum / book.rates.count : 0
  end
  def nickname(book)
    book.user_id.nil? ? "no user" : (User.find(book.user_id).nickname)
  end
end

app/views/books/_chapter_fields.html.erb
<div id= "<%=@count%>" class="tab-pane fade">
  <div class="nested-fields">
    <div class="field">

      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
      <br>
      <br>
      <%= f.label :text %>
      <br>
      <%= f.text_area :text, :class => "full-width-input" %>
      <br>
      <%= link_to "delete chapter", delete_chapter_path(book_id: @book.id, chapter_id: @book.chapters[@count].id), remote: true%>
    </div>

  </div>

</div>

app/views/books/_chapter_preview.html.erb
<div class="chapter-preview col-lg-3 col-md-3 col-sm-12 col-md-offset-1 col-lg-offset-1 " >
  <h3><%= f.book.title %></h3>
  <h4><%= f.title %></h4>
  <h5>Author: <%= nickname f.book %></h5>
  <aricle><%= f.text %></aricle>
  <!--линк на ридер-->
  <% link_to %>


</div>

app/views/books/_form.html.erb
<div id="chapters">
    <% if false#@book.nil? %>
        <%@book = Book.create(title: "No title")%>
    <% end%>
    <%= form_for [current_user, @book] do |f| %>
        <div class="field">
          <%= f.label :title %>
          <br/>
          <%= f.text_field :title %>
        </div>

        <h3>Chapters</h3>

            <ul class="nav nav-pills">
              <% @count = 0 %>
              <% @book.chapters.each do |chapter| %>
                <li><a data-toggle="pill" href="#<%= @count %>" ><%= chapter.title %></a></li>
                <%@count+=1%>
              <%end %>
              <li><%= link_to "+", add_chapter_path(book_id: @book.id), remote: true, data: { toggle: 'pill'} %></li>
              </ul>
            <div class="tab-content">
              <% @count = 0 %>
              <%= f.fields_for :chapters do |chapters| %>
                  <%= render 'chapter_fields', f: chapters %>
                  <% @count += 1%>
              <% end %>
            </div>

        <%= f.submit %>
    <% end %>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>
<table>
  <% @books.each do |book| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

        <td class="list_description">

          <dl>
            <dt><%= book.title %></dt>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', user_book_path(id: book.id, user_id: book.user_id) %><br/>
          <%= link_to 'Edit', edit_user_book_path(id: book.id, user_id: book.user_id) %><br/>
          <%= link_to 'Destroy', user_book_path(id: book.id, user_id: book.user_id), method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>
<br />
<%= link_to 'New book', new_user_book_path(current_user) %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', user_page_path%>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @book.title %></h1>
<!--h2 Добавить линк на user page -->
<h2>By  <%= @book.user_id %></h2>


<div class="row containter">
  <div class="col-md-12 col-lg-12 col-sm-12 ">
    <h3>Chapters:</h3>
    <ul>
      <% @book.chapters.each do |c| %>
          <!-- обернуть в button to на ридер -->
          <%= render 'books/chapter_preview', f: c %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-12 col-lg-12 col-sm-12 links-container">
    <%if current_user %>
        <%= link_to 'Edit', edit_user_book_path(user_id: current_user.id, id: @book) %>
    <% end %>
    <%= link_to 'Back', user_path(@book.user_id) %>
  </div>
</div>