config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :admins
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations" },
             path: "auth", path_names: { sign_in: 'login', sign_out: 'logout',
                                         password: 'secret', confirmation: 'verification',
                                         unlock: 'unblock', registration: 'register',
                                         sign_up: 'signup' }
  resources :users do
    resources :books do
      resources :chapters
    end
  end

  resources :books do
    resources :chapters
  end

  get 'home' => "catalog#index", as: :home
  get 'user/:user_id' => "users#show", as: :user_page
  get "user/:user_id/books/:book_id/add" => "books#add_chapter", as: :add_chapter
  get "user/:user_id/book/:book_id/chapter/:chapter_id/delete" => "books#delete_chapter", as: :delete_chapter

   root 'catalog#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ActiveRecord::Base
  ratyrate_rateable "lol"
  validates :title, presence: true

  # validates :image_url, format: {
  #              with: %r{\.(gif|jpg|png)\Z}i,
  #              message: 'Only GIF/PNG/JPEG image formats are supported'
  #
  #          }



  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :positions, as: :positionable
  has_many :comments, as: :commentable
  has_many :tags
  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true


end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belong_to :comentable, polymorphic: true
  has_many :likes, as: :likable

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likable, polimorphic: true

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/position.rb
class Position <ActiveRecord::Base
  belongs_to :positionable, polymorphic: true
end

app/models/rate.rb
class Rate <ActiveRecord::Base
  belongs_to :ratable, polymorphic: true
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/tag.rb
class Tag <ActiveRecord::Base
  has_and_belongs_to_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  has_many :books
  has_many :comments, as: :commentable
  has_many :likes, as: :likable
  has_many :positions, as: :positionable


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :add_chapter, :delete_chapter]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]

  def index
    @books = Book.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @book }
    end
  end

  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  def new
    @book =  Book.create(user_id: current_user.id, title: "No title")
  end

  def edit
  end

  def create
  @book = Book.update(book_params)
  @book.user_id = current_user.id
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_chapter
    @book.chapters.push Chapter.create(book_id: @book.id, title: "No title")
  end

  def delete_chapter
    @book.chapters.find(params[:chapter_id]).destroy
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(book_params)
        format.html { redirect_to @book, :notice => 'Book was successfully updated.' }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  def rate
    mark = params[:rate]
    if(rate > 0 && rate < 6)
      user = User.find_by_id(params[:user_id])
      book = Book.find_by_id(params[:book_id])
      rate = Rate.where(user_id: user.id, book_id: book.id).first
    end
  end




  def destroy
    @book.destroy
    @books = Book.all
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private

  def set_book
    @book = Book.find(params[:book_id] || params[:id])
  end

  def book_params
    params.require(:book).permit(
        :title, :user_id, :category,:tags,
        chapters_attributes: [:id, :text, :title, :done, :_destroy])
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def index
    @chapters = Chapter.order('created_at DESC').all.where('chapters.book_id IS NOT NULL')

  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end


  private
    def set_user
      @user = User.find_by_id(params[:user_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def rating(book)
    book.rates.count > 0 ? book.rates.all.sum / book.rates.count : 0
  end
  def nickname(book)
    book.user_id.nil? ? "no user" : (User.find(book.user_id).nickname)
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def first_name
    name = @user.first_name
    if name.nil?
      "No name"
    else
      name
    end
  end
  def last_name
    name = @user.last_name
    if name.nil?
      "No name"
    else
      name
    end
  end
end

app/views/catalog/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<h1>Last updated books:</h1>
<div class='row'>
  <% @chapters.each do |chapter| %>
      <%= link_to user_book_path(user_id: chapter.book.user_id, id: chapter.book.id) do %>
          <%if false%>
              <div class="chapter-preview col-lg-4 col-md-4 col-sm-12" >
                <h3><%= chapter.book.title %></h3>
                <h4><%= chapter.title %></h4>
                <h5>Author: <%= nickname chapter.book %></h5>
                <aricle><%= %></aricle>
              </div>
          <% end %>
          <%= render 'books/chapter_preview', f: chapter %>


      <% end %>
  <% end %>

</div>

app/views/chapters/_form.html.erb
<%= form_for(chapter) do |f| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>


  <div class="actions">
    <%= link_to '>', book_chapters_path(@book, params ), method: :post  %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/edit.js.erb
/**
 * Created by topinambour on 30.3.16.
 */
$('#edit_chapter').html('<%= j render partial:'form', locals: {chapter: @chapter}%>');

app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chapters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.title %></td>

        <td><%= chapter.text %></td>
        <td><%= chapter.book_id %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/new.js.erb
/**
 * Created by topinambour on 30.3.16.
 */
$('#edit_chapter').html('<%= j render partial:'form', locals: {chapter: @chapter}%>');

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chapter.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @chapter.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= current_user.id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @chapter.book_id %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>